export const contactFormSeed = {
  title: 'Contact Form',
  fields: [
    {
      name: 'full-name',
      label: 'Full Name',
      type: 'text' as const,
      required: true,
    },
    {
      name: 'email',
      label: 'Email',
      type: 'email' as const,
      required: true,
    },
    {
      name: 'phone',
      label: 'Phone',
      type: 'text' as const,
      required: false,
    },
    {
      name: 'message',
      label: 'Message',
      type: 'textarea' as const,
      required: true,
    },
  ],
  confirmationMessage: {
    root: {
      type: 'root' as const,
      children: [
        {
          type: 'heading' as const,
          children: [
            {
              type: 'text' as const,
              detail: 0,
              format: 0,
              mode: 'normal' as const,
              style: '',
              text: 'Thank you for your message!',
              version: 1,
            },
          ],
          direction: 'ltr' as const,
          format: '',
          indent: 0,
          tag: 'h2' as const,
          version: 1,
        },
        {
          type: 'paragraph' as const,
          children: [
            {
              type: 'text' as const,
              detail: 0,
              format: 0,
              mode: 'normal' as const,
              style: '',
              text: 'We have received your contact form submission and will get back to you soon.',
              version: 1,
            },
          ],
          direction: 'ltr' as const,
          format: '',
          indent: 0,
          textFormat: 0,
          version: 1,
        },
      ],
      direction: 'ltr' as const,
      format: '',
      indent: 0,
      version: 1,
    },
  },
  confirmationType: 'message' as const,
  emails: [
    {
      emailFrom: '"Page Mansions" <noreply@pagemansions.com>',
      emailTo: '{{email}}',
      subject: 'Thank you for contacting Page Mansions',
      message: {
        root: {
          type: 'root',
          children: [
            {
              type: 'paragraph',
              children: [
                {
                  type: 'text',
                  detail: 0,
                  format: 0,
                  mode: 'normal',
                  style: '',
                  text: 'Dear {{full-name}},',
                  version: 1,
                },
              ],
              direction: 'ltr',
              format: '',
              indent: 0,
              textFormat: 0,
              version: 1,
            },
            {
              type: 'paragraph',
              children: [
                {
                  type: 'text',
                  detail: 0,
                  format: 0,
                  mode: 'normal',
                  style: '',
                  text: 'Thank you for contacting Page Mansions. We have received your message and will respond to you shortly.',
                  version: 1,
                },
              ],
              direction: 'ltr',
              format: '',
              indent: 0,
              textFormat: 0,
              version: 1,
            },
            {
              type: 'paragraph',
              children: [
                {
                  type: 'text',
                  detail: 0,
                  format: 0,
                  mode: 'normal',
                  style: '',
                  text: 'Best regards,',
                  version: 1,
                },
              ],
              direction: 'ltr',
              format: '',
              indent: 0,
              textFormat: 0,
              version: 1,
            },
            {
              type: 'paragraph',
              children: [
                {
                  type: 'text',
                  detail: 0,
                  format: 0,
                  mode: 'normal',
                  style: '',
                  text: 'The Page Mansions Team',
                  version: 1,
                },
              ],
              direction: 'ltr',
              format: '',
              indent: 0,
              textFormat: 0,
              version: 1,
            },
          ],
          direction: 'ltr',
          format: '',
          indent: 0,
          version: 1,
        },
      },
    },
  ],
}
